version: '3'
services:
  app:
    build: .
    image: myapp:latest
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydb
    volumes:
      - ./world.sql:/docker-entrypoint-initdb.d/world.sql
    ports:
      - "3306:3306"
    restart: always

