name: A workflow for my Hello World App
on: push

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Unit Tests
        run: mvn -Dtest=com.napier.sem.MyTest test
      - name: Package and Run docker compose
        run: |
          mvn package -DskitTests
          docker-compose up --abort-on-container-exit
      - name: Setup network
        run: |
          docker network create --driver bridge my-custom-network
      - name: Pull MySQL
        run: |
          docker pull mysql:5.7
      - name: Run MySQL
        run: |
          docker run -d --name db --network my-custom-network \
          -e MYSQL_ROOT_PASSWORD=example \
          -e MYSQL_DATABASE=mydb \
          -v ${{ github.workspace }}/world.sql:/docker-entrypoint-initdb.d/world.sql \
          mysql:5.7
      - name: Build with Maven
        run: mvn package
      - name: Build
        run: docker build -t se_methods .
      - name: Run image
        run: docker run --network my-custom-network --name semcontainer se_methods
      - name: view logs
        run: docker logs semcontainer
